# Generated by Django 3.0.8 on 2020-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignmentDescription',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assignmentFile',
            field=models.FileField(null=True, upload_to='static/AssignmentFiles'),
        ),
    ]
