# Generated by Django 3.0.8 on 2020-12-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20201228_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignmentDescription',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignmentFile',
            field=models.FileField(blank=True, null=True, upload_to='static/AssignmentFiles'),
        ),
    ]
